services:

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app_network
    container_name: frontend_srex
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    networks:
      - app_network
    container_name: backend_srex
    ports:
      - "8080:8080"
      

networks:
  app_network:
    driver: bridge
